from .address_views import *
from .agendamento_views import *
from .anamnese_views import *
from .appointment_views import *
from .cidadao_views import *
from .dependente_views import *
from .documento_views import *
from .email_views import *
from .enfermeiro_views import *
from .exam_views import *
from .fila_atendimento_views import *
from .focus_priority_views import *
from .grupo_vulneravel_views import *
from .hypothesis_views import *
from .medication_appoi_views import *
from .medication_ubs_views import *
from .medication_views import *
from .medico_views import *
from .pessoa_views import *
from .record_vaccine_views import *
from .telefone_views import *
from .ubs_views import *
from .vaccine_ubs_views import *
from .vaccine_views import *