from .cidadao_form import *
from .agendamento_form import *
from .anamnese_form import *
from .enfermeiro_form import *
from .medico_form import *
from .appointment_form import *
from .exam_form import *
from .fila_form import *
from .dependente_form import *
from .documento_form import *
from .email_form import *
from .telefone_form import *
from .ubs_form import *
from .medication_form import *
from .medication_ubs_form import *
from .grupo_form import *
from .vaccine_form import *
from .vaccine_ubs_form import *
from .record_vaccine_form import *
from .hypothesis_form import *
from .medication_appoi_form import *