from .address_form import AddressForm
from .agendamento_form import AgendamentoForm
from .anamnese_form import AnamneseForm
from .appointment_form import AppointmentForm
from .cidadao_form import CidadaoForm
from .dependente_form import DependenteForm
from .documento_form import DocumentoForm
from .email_form import EmailForm
from .enfermeiro_form import EnfermeiroForm
from .exam_form import ExamForm
from .fila_atendimento_form import FilaAtendimentoForm as FilaForm
from .focus_priority_form import FocusPriorityForm
from .grupo_vulneravel_form import GrupoVulneravelForm
from .hypothesis_form import HypothesisForm
from .medication_form import MedicationForm
from .medication_appoi_form import MedicationAppoiForm
from .medication_ubs_form import MedicationUbsForm
from .medico_form import MedicoForm
from .pessoa_form import PessoaForm
from .telefone_form import TelefoneForm
from .ubs_form import UbsForm
from .record_vaccine_form import RecordVaccineForm
from .vaccine_form import VaccineForm
from .vaccine_ubs_form import VaccineUbsForm