# Generated by Django 6.0.3 on 2026-03-25 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField()),
                ('hora_agendamento', models.TimeField()),
                ('posicao_atual', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('EM_ESPERA', 'Em espera')], default='PENDENTE', max_length=20)),
                ('prioridade_calculada', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa', models.CharField(max_length=255)),
                ('estado_civil', models.CharField(choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('UNIAO_ESTAVEL', 'União estável')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoVulneravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(choices=[('RECEM_NASCIDOS', 'Recém-nascidos'), ('CRIANCA', 'Crianças'), ('GESTANTE', 'Gestantes'), ('PUERPERA', 'Puérperas'), ('IDOSO', 'Idosos'), ('DOENCA_CRONICA', 'Doenças crônicas'), ('DEFICIENCIA', 'Pessoa com deficiência'), ('SAUDE_MENTAL', 'Transtornos mentais'), ('SITUACAO_DE_RUA', 'Situação de rua'), ('INDIGENA', 'População indígena'), ('QUILOMBOLA', 'População quilombola'), ('PRIVADO_LIBERDADE', 'Privado de liberdade'), ('USUARIO_DROGAS', 'Usuários de drogas'), ('HIV_IST', 'HIV/IST'), ('ADOLESCENTE', 'Adolescentes'), ('VITIMA_VIOLENCIA', 'Vítima de violência')], max_length=50, unique=True)),
                ('peso_prioridade', models.IntegerField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_medication', models.CharField(max_length=100)),
                ('category_med', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vaccine', models.CharField(max_length=100)),
                ('vaccine_manufacturer', models.CharField(max_length=100)),
                ('prevents', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('reason', models.TextField()),
                ('life_habits', models.TextField()),
                ('scheduling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='ubs.agendamento')),
            ],
        ),
        migrations.CreateModel(
            name='Cidadao',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ubs.pessoa')),
                ('num_sus', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('naturalidade', models.CharField(max_length=100)),
                ('ocupacao', models.CharField(max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubs.address')),
                ('grupos', models.ManyToManyField(blank=True, related_name='cidadaos', to='ubs.grupovulneravel')),
            ],
            bases=('ubs.pessoa',),
        ),
        migrations.CreateModel(
            name='Enfermeiro',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ubs.pessoa')),
                ('cip', models.CharField(max_length=50)),
            ],
            bases=('ubs.pessoa',),
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ubs.pessoa')),
                ('crm', models.CharField(max_length=20, unique=True)),
                ('especialidade', models.CharField(max_length=100)),
            ],
            bases=('ubs.pessoa',),
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=50)),
                ('dependente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_de', to='ubs.pessoa')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='ubs.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CPF', 'CPF'), ('RG', 'RG'), ('CNH', 'CNH')], max_length=30)),
                ('numero_documento', models.CharField(max_length=50)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='ubs.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_exam', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('LAB', 'Laboratorial'), ('IMG', 'Imagem')], max_length=20)),
                ('status', models.CharField(choices=[('REQUESTED', 'Solicitado'), ('DONE', 'Realizado')], max_length=20)),
                ('result', models.TextField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='ubs.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Hypothesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100)),
                ('cid', models.CharField(max_length=20)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hipoteses', to='ubs.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationAppoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(max_length=50)),
                ('via', models.CharField(choices=[('ORAL', 'Oral'), ('IV', 'Intravenosa'), ('IM', 'Intramuscular')], max_length=20)),
                ('frequency_days', models.IntegerField()),
                ('duraction_adm', models.IntegerField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicacoes', to='ubs.appointment')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubs.medication')),
            ],
        ),
        migrations.CreateModel(
            name='Ubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubs', to='ubs.address')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('PESSOA', 'Pessoa'), ('UBS', 'UBS')], max_length=10)),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='ubs.pessoa')),
                ('ubs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='ubs.ubs')),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='ubs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubs.ubs'),
        ),
        migrations.CreateModel(
            name='MedicationUbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_lote', models.CharField(max_length=50)),
                ('available_quantity', models.IntegerField()),
                ('validity', models.DateField()),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubs.medication')),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubs.ubs')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('PESSOA', 'Pessoa'), ('UBS', 'UBS')], max_length=10)),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='ubs.pessoa')),
                ('ubs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='ubs.ubs')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='ubs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubs.ubs'),
        ),
        migrations.CreateModel(
            name='FocusPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacao', models.CharField(max_length=100)),
                ('grupo_vulneravel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubs.grupovulneravel')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubs.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineUbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(blank=True, choices=[('VERY_HIGH', 'Muito Alta'), ('HIGH', 'Alta'), ('MEDIUM', 'Média'), ('LOW', 'Baixa')], max_length=10, null=True)),
                ('dose', models.CharField(max_length=50)),
                ('lote', models.CharField(max_length=50)),
                ('available_quan', models.IntegerField()),
                ('validity', models.DateField()),
                ('focus_priority', models.ManyToManyField(blank=True, related_name='vacinas', to='ubs.focuspriority')),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='ubs.ubs')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='ubs.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_anamnese', models.DateField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('pressao_arterial', models.CharField(max_length=20)),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubs.cidadao')),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cidadao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubs.cidadao'),
        ),
        migrations.CreateModel(
            name='RecordVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubs.ubs')),
                ('vaccine_ubs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubs.vaccineubs')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubs.cidadao')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubs.enfermeiro')),
            ],
        ),
        migrations.CreateModel(
            name='FilaAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atendimento', models.CharField(choices=[('CONSULTA', 'Consulta'), ('VACINA', 'Vacina')], max_length=20)),
                ('data_fila', models.DateField()),
                ('quantidade_maxima', models.IntegerField()),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubs.ubs')),
                ('vacina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubs.vaccine')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubs.medico')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubs.medico'),
        ),
    ]
